In [2]:
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/coins/markets"

params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 250,
    "page": 1,
    "sparkline": False
}

response = requests.get(url, params=params)
data = response.json()

df = pd.DataFrame(data)

df = df[["id","symbol","name","current_price","market_cap","market_cap_rank",
         "total_volume","circulating_supply","total_supply","ath","atl","last_updated"]]

df.to_csv("crypto_market_data.csv", index=False)

In [3]:
url = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"

params = {
    "vs_currency": "usd",
    "days": "365"
}

response = requests.get(url, params=params)
data = response.json()

prices = data["prices"]

btc_df = pd.DataFrame(prices, columns=["timestamp","price_usd"])

btc_df["date"] = pd.to_datetime(btc_df["timestamp"], unit="ms").dt.date

btc_df = btc_df[["date","price_usd"]]

btc_df.to_csv("bitcoin_prices.csv", index=False)

In [4]:
import pandas as pd

oil_url = "https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv"

oil_df = pd.read_csv(oil_url)

oil_df.to_csv("oil_prices.csv", index=False)

In [6]:
!pip install yfinance

import yfinance as yf
import pandas as pd

tickers = ["^GSPC","^IXIC","^NSEI"]

stock_data = yf.download(tickers, start="2020-01-01", end="2025-01-01")

stock_df = stock_data.stack(level=1).reset_index()

stock_df.to_csv("stock_prices.csv", index=False)

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.9.2)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.0.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.14.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

/tmp/ipykernel_444/3549269927.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stock_data = yf.download(tickers, start="2020-01-01", end="2025-01-01")
[*********************100%***********************]  3 of 3 completed
/tmp/ipykernel_444/3549269927.py:10: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stock_df = stock_data.stack(level=1).reset_index()

In [7]:
import pandas as pd
crypto = pd.read_csv("crypto_market_data.csv")
oil = pd.read_csv("oil_prices.csv")
stocks = pd.read_csv("stock_prices.csv")
btc = pd.read_csv("bitcoin_prices.csv")
print(crypto)
print(oil)
print(stocks)
print(btc)

                           id symbol                      name  current_price  \
0                     bitcoin    btc                   Bitcoin   67959.000000
1                    ethereum    eth                  Ethereum    2002.580000
2                      tether   usdt                    Tether       0.999815
3                 binancecoin    bnb                       BNB     627.760000
4                      ripple    xrp                       XRP       1.350000
..                        ...    ...                       ...            ...
245             akash-network    akt             Akash Network       0.383594
246  quantum-resistant-ledger    qrl  Quantum Resistant Ledger       1.390000
247                    cash-4   cash                      CASH       1.000000
248       precious-metals-usd  pmusd       Precious Metals USD       0.988173
249                   cap-usd   cusd                   Cap USD       1.001000

        market_cap  market_cap_rank  total_volume  circulating_supply  \
0    1360439595564                1  4.521852e+10        1.999980e+07
1     241854145730                2  2.130865e+10        1.206920e+08
2     183868914606                3  7.051148e+10        1.839095e+11
3      85608529251                4  8.605146e+08        1.363584e+08
4      82948632505                5  2.200705e+09        6.122783e+10
..             ...              ...           ...                 ...
245      111634638              246  1.328202e+07        2.892543e+08
246      109810815              247  1.076470e+05        7.839296e+07
247      108473596              248  1.354805e+07        1.084558e+08
248      108425417              249  9.749350e+05        1.097012e+08
249      108422522              250  1.052640e+05        1.091973e+08

     total_supply         ath        atl              last_updated
0    1.999980e+07  126080.000  67.810000  2026-03-09T10:14:21.079Z
1    1.206920e+08    4946.050   0.432979  2026-03-09T10:14:21.489Z
2    1.893765e+11       1.320   0.572521  2026-03-09T10:14:17.427Z
3    1.363584e+08    1369.990   0.039818  2026-03-09T10:14:20.825Z
4    9.998570e+10       3.650   0.002686  2026-03-09T10:14:16.732Z
..            ...         ...        ...                       ...
245  2.894799e+08       8.070   0.164994  2026-03-09T10:14:17.682Z
246  7.839296e+07       3.870   0.041170  2026-03-09T10:14:17.840Z
247  1.084558e+08       1.058   0.975346  2026-03-09T10:14:17.709Z
248  1.097012e+08       1.037   0.955534  2026-03-09T10:14:17.717Z
249  1.091973e+08       1.170   0.946058  2026-03-09T10:14:17.692Z

[250 rows x 12 columns]
             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10104  2026-02-24  65.62
10105  2026-02-25  65.30
10106  2026-02-26  65.10
10107  2026-02-27  66.96
10108  2026-03-02  71.13

[10109 rows x 2 columns]
            Date Ticker         Close          High           Low  \
0     2020-01-01  ^NSEI  12182.500000  12222.200195  12165.299805
1     2020-01-02  ^GSPC   3257.850098   3258.139893   3235.530029
2     2020-01-02  ^IXIC   9092.190430   9093.429688   9010.889648
3     2020-01-02  ^NSEI  12282.200195  12289.900391  12195.250000
4     2020-01-03  ^GSPC   3234.850098   3246.149902   3222.340088
...          ...    ...           ...           ...           ...
3748  2024-12-30  ^IXIC  19486.789062  19622.929688  19342.509766
3749  2024-12-30  ^NSEI  23644.900391  23915.349609  23599.300781
3750  2024-12-31  ^GSPC   5881.629883   5929.740234   5868.859863
3751  2024-12-31  ^IXIC  19310.789062  19563.720703  19283.410156
3752  2024-12-31  ^NSEI  23644.800781  23689.849609  23460.449219

              Open        Volume
0     12202.150391  3.041000e+05
1      3244.669922  3.459930e+09
2      9039.459961  2.862700e+09
3     12198.549805  4.077000e+05
4      3226.360107  3.484700e+09
...            ...           ...
3748  19460.410156  8.384090e+09
3749  23796.900391  3.649000e+05
3750   5919.740234  3.128350e+09
3751  19551.359375  8.873030e+09
3752  23560.599609  1.936000e+05

[3753 rows x 7 columns]
           date     price_usd
0    2025-03-10  80751.138933
1    2025-03-11  78783.940579
2    2025-03-12  82799.108029
3    2025-03-13  83884.245788
4    2025-03-14  81098.900524
..          ...           ...
361  2026-03-06  70874.986871
362  2026-03-07  68148.283400
363  2026-03-08  67271.190778
364  2026-03-09  66036.157824
365  2026-03-09  67964.300917

[366 rows x 2 columns]

In [8]:
import requests
import pandas as pd
import time

def get_crypto_price(coin):

    url = f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart"

    params = {
        "vs_currency": "usd",
        "days": 365
    }

    try:
        response = requests.get(url, params=params)
        print(coin, "status:", response.status_code)

        if response.status_code != 200:
            return pd.DataFrame()

        data = response.json()
        prices = data["prices"]

        df = pd.DataFrame(prices, columns=["timestamp","price_usd"])

        df["date"] = pd.to_datetime(df["timestamp"], unit="ms").dt.date
        df["coin_id"] = coin

        df = df[["coin_id","date","price_usd"]]

        return df

    except:
        print("API error for", coin)
        return pd.DataFrame()

In [9]:
bitcoin = get_crypto_price("bitcoin")
time.sleep(5)

ethereum = get_crypto_price("ethereum")
time.sleep(5)

tether = get_crypto_price("tether")

bitcoin status: 200
ethereum status: 200
tether status: 200

In [10]:
import pandas as pd
crypto = pd.read_csv("crypto_market_data.csv")
oil = pd.read_csv("oil_prices.csv")
stocks = pd.read_csv("stock_prices.csv")
btc = pd.read_csv("bitcoin_prices.csv")

print(crypto)
print(oil)
print(stocks)
print(btc)

                           id symbol                      name  current_price  \
0                     bitcoin    btc                   Bitcoin   67959.000000
1                    ethereum    eth                  Ethereum    2002.580000
2                      tether   usdt                    Tether       0.999815
3                 binancecoin    bnb                       BNB     627.760000
4                      ripple    xrp                       XRP       1.350000
..                        ...    ...                       ...            ...
245             akash-network    akt             Akash Network       0.383594
246  quantum-resistant-ledger    qrl  Quantum Resistant Ledger       1.390000
247                    cash-4   cash                      CASH       1.000000
248       precious-metals-usd  pmusd       Precious Metals USD       0.988173
249                   cap-usd   cusd                   Cap USD       1.001000

        market_cap  market_cap_rank  total_volume  circulating_supply  \
0    1360439595564                1  4.521852e+10        1.999980e+07
1     241854145730                2  2.130865e+10        1.206920e+08
2     183868914606                3  7.051148e+10        1.839095e+11
3      85608529251                4  8.605146e+08        1.363584e+08
4      82948632505                5  2.200705e+09        6.122783e+10
..             ...              ...           ...                 ...
245      111634638              246  1.328202e+07        2.892543e+08
246      109810815              247  1.076470e+05        7.839296e+07
247      108473596              248  1.354805e+07        1.084558e+08
248      108425417              249  9.749350e+05        1.097012e+08
249      108422522              250  1.052640e+05        1.091973e+08

     total_supply         ath        atl              last_updated
0    1.999980e+07  126080.000  67.810000  2026-03-09T10:14:21.079Z
1    1.206920e+08    4946.050   0.432979  2026-03-09T10:14:21.489Z
2    1.893765e+11       1.320   0.572521  2026-03-09T10:14:17.427Z
3    1.363584e+08    1369.990   0.039818  2026-03-09T10:14:20.825Z
4    9.998570e+10       3.650   0.002686  2026-03-09T10:14:16.732Z
..            ...         ...        ...                       ...
245  2.894799e+08       8.070   0.164994  2026-03-09T10:14:17.682Z
246  7.839296e+07       3.870   0.041170  2026-03-09T10:14:17.840Z
247  1.084558e+08       1.058   0.975346  2026-03-09T10:14:17.709Z
248  1.097012e+08       1.037   0.955534  2026-03-09T10:14:17.717Z
249  1.091973e+08       1.170   0.946058  2026-03-09T10:14:17.692Z

[250 rows x 12 columns]
             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10104  2026-02-24  65.62
10105  2026-02-25  65.30
10106  2026-02-26  65.10
10107  2026-02-27  66.96
10108  2026-03-02  71.13

[10109 rows x 2 columns]
            Date Ticker         Close          High           Low  \
0     2020-01-01  ^NSEI  12182.500000  12222.200195  12165.299805
1     2020-01-02  ^GSPC   3257.850098   3258.139893   3235.530029
2     2020-01-02  ^IXIC   9092.190430   9093.429688   9010.889648
3     2020-01-02  ^NSEI  12282.200195  12289.900391  12195.250000
4     2020-01-03  ^GSPC   3234.850098   3246.149902   3222.340088
...          ...    ...           ...           ...           ...
3748  2024-12-30  ^IXIC  19486.789062  19622.929688  19342.509766
3749  2024-12-30  ^NSEI  23644.900391  23915.349609  23599.300781
3750  2024-12-31  ^GSPC   5881.629883   5929.740234   5868.859863
3751  2024-12-31  ^IXIC  19310.789062  19563.720703  19283.410156
3752  2024-12-31  ^NSEI  23644.800781  23689.849609  23460.449219

              Open        Volume
0     12202.150391  3.041000e+05
1      3244.669922  3.459930e+09
2      9039.459961  2.862700e+09
3     12198.549805  4.077000e+05
4      3226.360107  3.484700e+09
...            ...           ...
3748  19460.410156  8.384090e+09
3749  23796.900391  3.649000e+05
3750   5919.740234  3.128350e+09
3751  19551.359375  8.873030e+09
3752  23560.599609  1.936000e+05

[3753 rows x 7 columns]
           date     price_usd
0    2025-03-10  80751.138933
1    2025-03-11  78783.940579
2    2025-03-12  82799.108029
3    2025-03-13  83884.245788
4    2025-03-14  81098.900524
..          ...           ...
361  2026-03-06  70874.986871
362  2026-03-07  68148.283400
363  2026-03-08  67271.190778
364  2026-03-09  66036.157824
365  2026-03-09  67964.300917

[366 rows x 2 columns]

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!ls /content/drive/MyDrive/

 3718501-1-MAY_provisional_marksheet.pdf
'AADHAAR_CARD_BHARGAVI (1).pdf'
 AADHAAR_CARD_BHARGAVI.pdf
'ABC_ID (1).pdf'
 ABC_ID.pdf
'active or passive voice.jpg'
'Audio from Kalyan'
'Bank Account-Compunet updated list.gsheet'
 bhargavi{1}.docx
'BHARGAVI certificates'
'Bhargavi certificates.pdf'
'Bhargavi K_Offer Letter_GL-OPGDM-CI (1).pdf'
'Bhargavi K_Offer Letter_GL-OPGDM-CI.pdf'
'BHARGAVIPHOTO-1 (1).jpg'
 BHARGAVIPHOTO-1.jpg
'Bhargavi photo (3).jpg'
'BhargaviResume (1).pdf'
 Bhargavi_Resume_Copy.pdf
'Bhargavi Resume.pdf'
 BhargaviResume.pdf
 bharu.jpg
'bio botany (1).jpeg'
'bio botany (2).jpeg'
'bio botany.jpeg'
 Bio-Botany.jpeg
 bio-botany.pdf
'Bio Botany.pdf'
'Bio Botany test.jpg'
'biology (1).pdf'
 biology.jpeg
'Biology objective test.jpeg'
 biology.pdf
 Biology.pdf
'biology quiz.jpeg'
'biology revision (1).pdf'
'biology revision.pdf'
'biology test.jpeg'
'bio zoology.jpeg'
 bio-zoology.jpeg
 Bio-zoology.jpeg
 Bio-Zoology.jpeg
 Bio-zoology.jpg
'Bio zoology test.jpg'
 Botany.jpeg
'but now is there any changes he might give or not.gsheet'
 certificate.pdf
'Chemistry (1).jpeg'
'chemistry (1).jpg'
'chemistry(1).jpg'
'Chemistry (1).pdf'
'Chemistry (2).jpeg'
'chemistry (2).jpg'
'Chemistry (2).pdf'
'Chemistry (3).jpeg'
'chemistry (3).jpg'
 chemistry...coals.jpg
 chemistry..fuels.jpg
 Chemistry.jpeg
 chemistry.jpg
'Chemistry objective test.jpeg'
 Chemistry.pdf
 chemistryquiz.jpg
'chemistry...refining of petroleum (1).jpeg'
'chemistry...refining of petroleum.jpeg'
'Chemistry test (1).pdf'
'Chemistry test (2).pdf'
'Chemistry test (3).pdf'
'Chemistry test (4).pdf'
'Chemistry test (5).pdf'
'chemistry test.jpeg'
'chemistry test.pdf'
'Chemistry test.pdf'
 Classroom
 Codes.zip
'Colab Notebooks'
'Copy of Weekly progress report.gsheet'
'c programming.pdf'
 crypto_project
 Data_Science
'Document from Bhargavi (1).pdf'
'Document from Bhargavi (2).pdf'
'Document from Bhargavi (3).pdf'
'Document from Bhargavi (4).pdf'
'Document from Bhargavi💜💙(Amy Jackson) (1).pdf'
'Document from Bhargavi💜💙(Amy Jackson) (2).pdf'
'Document from Bhargavi💜💙(Amy Jackson) (3).pdf'
'Document from Bhargavi💜💙(Amy Jackson).pdf'
'Document from Bhargavi.pdf'
'Document from Bharu Bhargavi🌟'
'Document from Bharu Bhargavi🌟 (1)'
'Document from Bharu Bhargavi🌟 (2)'
'Document from Bharu Bhargavi🌟.pdf'
 Documents.zip
'Edited - Bio botany (1).jpeg'
'Edited - Bio botany (2).jpeg'
'Edited - Bio botany.jpeg'
'Edited - Bio-Botany.jpeg'
'Edited - Bio Botany.pdf'
'Edited - Biology (1).pdf'
'Edited - Biology.pdf'
'Edited - Biology test.pdf'
'Edited - Bio-zoology (1).jpeg'
'Edited - Bio-zoology (1).pdf'
'Edited - Bio-zoology (2).pdf'
'Edited - Bio-zoology (3).pdf'
'Edited - Bio-zoology.jpeg'
'Edited - bio zoology.pdf'
'Edited - Bio-zoology.pdf'
'Edited - Bio zoology test.jpeg'
'Edited - bio-zoology test.pdf'
'Edited - English.jpeg'
 English.jpg
'English test (1).jpg'
'English test.jpg'
 File_Handling_in_Python.ipynb
 flowers
'fuels (1).jpg'
 fuels.jpg
'Generated PDF from Image Files (1).pdf'
'Generated PDF from Image Files.pdf'
'goal 14 life below water.pdf'
'hsh-jczw-fkd - Jan 12, 2021.pdf'
'https:  images..txt'
 IMG-20240331-WA0004.jpg
 IMG-20240331-WA0006.jpg
 IMG-20240331-WA0009.jpg
 IMG-20240331-WA0011.jpg
 IMG-20240331-WA0013.jpg
 IMG-20240331-WA0015.jpg
 IMG-20240331-WA0019.jpg
 IMG-20240331-WA0021.jpg
 IMG-20240414-WA0002.jpeg
 IMG-20240414-WA0003.jpg
 IMG-20240414-WA0004.jpeg
 IMG-20240414-WA0005.jpg
 IMG-20240414-WA0010.jpeg
 IMG-20240414-WA0011.jpg
 IMG-20240414-WA0012.jpeg
 IMG-20240414-WA0013.jpg
 IMG-20240414-WA0014.jpeg
 IMG-20240414-WA0015.jpg
 IMG-20240414-WA0016.jpeg
 IMG-20240414-WA0017.jpg
 IMG-20240414-WA0018.jpg
 IMG-20240414-WA0028.jpeg
 IMG-20240414-WA0031.jpg
 IMG-20240501-WA0004.jpg
 IMG_20241220_094155.jpg
'internship on data science.pdf'
 Karma_Yoga.xlsx
 Lambda_Filters_and_Map.ipynb
'let me see da....now itself after a few days befo....gsheet'
 List_Comprehension_in_python.ipynb
'Maths (1).jpeg'
'maths (1).jpg'
'maths (1).pdf'
'Maths (1).pdf'
'Maths (2).jpeg'
'Maths (2).pdf'
'Maths (3).jpeg'
'Maths (3).pdf'
'Maths (4).jpeg'
'Maths (4).pdf'
'Maths (5).pdf'
 Maths.jpeg
 maths.jpg
 maths.pdf
 Maths.pdf
'Maths test (1).pdf'
'Maths test (2).pdf'
'Maths test (3).pdf'
'Maths test (4).pdf'
'maths test.jpeg'
'maths test.pdf'
'Maths test.pdf'
'migration certificate.jpg'
'Neo4j (1).docx.pdf'
 Neo4j.docx.pdf
'New Static GK 2026 Updated (1).pdf'
'New Static GK 2026 Updated.pdf'
'now i need totally avoid her....right.....sometim....gsheet'
'online course.gsheet'
'payment_receipt (1).pdf'
 payment_receipt.pdf
'PEM 5th UNIT.docx.pdf'
'Personal memoranda.pdf'
'Photo from Bhargavi'
'Photo from Bhargavi (1)'
'Photo from Bhargavi (2)'
'Photo from Bhargavi (3)'
'Photo from Kalyan'
'Physics (1).jpeg'
'physics (1).jpg'
'physics (1).pdf'
'Physics (1).pdf'
'Physics (2).jpeg'
'physics (2).jpg'
'physics (3).jpg'
 physics.jpeg
 Physics.jpeg
 physics.jpg
 Physics.jpg
 physics.pdf
 Physics.pdf
'physics test (1).pdf'
'Physics test (1).pdf'
'Physics test (2).pdf'
'Physics test (3).pdf'
'Physics test (4).pdf'
'Physics test (5).pdf'
'Physics test-7.pdf'
'physics test.pdf'
'Physics test.pdf'
 provisional_certificate.jpg
'purpose statements (1).jpg'
'purpose statements.jpg'
'PYTHON LIBRARIES.gdoc'
'PYTHON LIBRARIES.pdf'
 Regular_Expressions_in_python.ipynb
'Resume Kalyan_PM.docx'
 Screenshot_20210108-154456.jpeg
 sdg.jpg
'Transfer_Certificate (1).jpg'
'transfer_certificate (1).pdf'
 Transfer_Certificate.jpg
 transfer_certificate.pdf
'UG_Marksheets (1).pdf'
 UG_Marksheets_BHARGAVI.pdf
 UG_Marksheets.pdf
'uhv 3.pdf'
'UHV Handout 1-Introduction to Value Education (1) (1).pdf'
'UHV Handout 2-Harmony in the Human Being.pdf'
'UHV Handout 4-Harmony in the Society.pdf'
'UHV Handout 5-Harmony in the Nature and Existence.pdf'
'uhv ques bank (1).pdf'
 UHV_UNIT4.pdf
 UHV_UNIT5.pdf
 ULIPRPR_XXXXXXX6604_26042022_8032.pdf
'unit 4 - part 2.pdf'
'Untitled Folder'
'Untitled Jam.pdf'
'Untitled spreadsheet (1).gsheet'
'Untitled spreadsheet.gsheet'
 VID-20201212-WA0031.mp4
 VID-20240415-WA0019.mp4
'Video from Bhargavi'
'Video from Kalyan'
'Video from Kalyan (1)'
'videoplayback (2).mp4'
'voj-wguc-yed - Nov 5, 2020.pdf'
'Weekly progress report.gsheet'
'Weekly progress report.xlsx'
'XII_MARK (1).pdf'
'XII_MARK (3).pdf'
 XII_MARK.pdf
'XII-maths delted portion - krishna.pdf'
'X_MARK (1).pdf'
'X_MARK (2).pdf'
 X_MARK.pdf

In [12]:
!mkdir /content/drive/MyDrive/crypto_project

mkdir: cannot create directory ‘/content/drive/MyDrive/crypto_project’: File exists

In [13]:
!ls /content/drive

MyDrive

In [14]:
!ls /content/drive/MyDrive

 3718501-1-MAY_provisional_marksheet.pdf
'AADHAAR_CARD_BHARGAVI (1).pdf'
 AADHAAR_CARD_BHARGAVI.pdf
'ABC_ID (1).pdf'
 ABC_ID.pdf
'active or passive voice.jpg'
'Audio from Kalyan'
'Bank Account-Compunet updated list.gsheet'
 bhargavi{1}.docx
'BHARGAVI certificates'
'Bhargavi certificates.pdf'
'Bhargavi K_Offer Letter_GL-OPGDM-CI (1).pdf'
'Bhargavi K_Offer Letter_GL-OPGDM-CI.pdf'
'BHARGAVIPHOTO-1 (1).jpg'
 BHARGAVIPHOTO-1.jpg
'Bhargavi photo (3).jpg'
'BhargaviResume (1).pdf'
 Bhargavi_Resume_Copy.pdf
'Bhargavi Resume.pdf'
 BhargaviResume.pdf
 bharu.jpg
'bio botany (1).jpeg'
'bio botany (2).jpeg'
'bio botany.jpeg'
 Bio-Botany.jpeg
 bio-botany.pdf
'Bio Botany.pdf'
'Bio Botany test.jpg'
'biology (1).pdf'
 biology.jpeg
'Biology objective test.jpeg'
 biology.pdf
 Biology.pdf
'biology quiz.jpeg'
'biology revision (1).pdf'
'biology revision.pdf'
'biology test.jpeg'
'bio zoology.jpeg'
 bio-zoology.jpeg
 Bio-zoology.jpeg
 Bio-Zoology.jpeg
 Bio-zoology.jpg
'Bio zoology test.jpg'
 Botany.jpeg
'but now is there any changes he might give or not.gsheet'
 certificate.pdf
'Chemistry (1).jpeg'
'chemistry (1).jpg'
'chemistry(1).jpg'
'Chemistry (1).pdf'
'Chemistry (2).jpeg'
'chemistry (2).jpg'
'Chemistry (2).pdf'
'Chemistry (3).jpeg'
'chemistry (3).jpg'
 chemistry...coals.jpg
 chemistry..fuels.jpg
 Chemistry.jpeg
 chemistry.jpg
'Chemistry objective test.jpeg'
 Chemistry.pdf
 chemistryquiz.jpg
'chemistry...refining of petroleum (1).jpeg'
'chemistry...refining of petroleum.jpeg'
'Chemistry test (1).pdf'
'Chemistry test (2).pdf'
'Chemistry test (3).pdf'
'Chemistry test (4).pdf'
'Chemistry test (5).pdf'
'chemistry test.jpeg'
'chemistry test.pdf'
'Chemistry test.pdf'
 Classroom
 Codes.zip
'Colab Notebooks'
'Copy of Weekly progress report.gsheet'
'c programming.pdf'
 crypto_project
 Data_Science
'Document from Bhargavi (1).pdf'
'Document from Bhargavi (2).pdf'
'Document from Bhargavi (3).pdf'
'Document from Bhargavi (4).pdf'
'Document from Bhargavi💜💙(Amy Jackson) (1).pdf'
'Document from Bhargavi💜💙(Amy Jackson) (2).pdf'
'Document from Bhargavi💜💙(Amy Jackson) (3).pdf'
'Document from Bhargavi💜💙(Amy Jackson).pdf'
'Document from Bhargavi.pdf'
'Document from Bharu Bhargavi🌟'
'Document from Bharu Bhargavi🌟 (1)'
'Document from Bharu Bhargavi🌟 (2)'
'Document from Bharu Bhargavi🌟.pdf'
 Documents.zip
'Edited - Bio botany (1).jpeg'
'Edited - Bio botany (2).jpeg'
'Edited - Bio botany.jpeg'
'Edited - Bio-Botany.jpeg'
'Edited - Bio Botany.pdf'
'Edited - Biology (1).pdf'
'Edited - Biology.pdf'
'Edited - Biology test.pdf'
'Edited - Bio-zoology (1).jpeg'
'Edited - Bio-zoology (1).pdf'
'Edited - Bio-zoology (2).pdf'
'Edited - Bio-zoology (3).pdf'
'Edited - Bio-zoology.jpeg'
'Edited - bio zoology.pdf'
'Edited - Bio-zoology.pdf'
'Edited - Bio zoology test.jpeg'
'Edited - bio-zoology test.pdf'
'Edited - English.jpeg'
 English.jpg
'English test (1).jpg'
'English test.jpg'
 File_Handling_in_Python.ipynb
 flowers
'fuels (1).jpg'
 fuels.jpg
'Generated PDF from Image Files (1).pdf'
'Generated PDF from Image Files.pdf'
'goal 14 life below water.pdf'
'hsh-jczw-fkd - Jan 12, 2021.pdf'
'https:  images..txt'
 IMG-20240331-WA0004.jpg
 IMG-20240331-WA0006.jpg
 IMG-20240331-WA0009.jpg
 IMG-20240331-WA0011.jpg
 IMG-20240331-WA0013.jpg
 IMG-20240331-WA0015.jpg
 IMG-20240331-WA0019.jpg
 IMG-20240331-WA0021.jpg
 IMG-20240414-WA0002.jpeg
 IMG-20240414-WA0003.jpg
 IMG-20240414-WA0004.jpeg
 IMG-20240414-WA0005.jpg
 IMG-20240414-WA0010.jpeg
 IMG-20240414-WA0011.jpg
 IMG-20240414-WA0012.jpeg
 IMG-20240414-WA0013.jpg
 IMG-20240414-WA0014.jpeg
 IMG-20240414-WA0015.jpg
 IMG-20240414-WA0016.jpeg
 IMG-20240414-WA0017.jpg
 IMG-20240414-WA0018.jpg
 IMG-20240414-WA0028.jpeg
 IMG-20240414-WA0031.jpg
 IMG-20240501-WA0004.jpg
 IMG_20241220_094155.jpg
'internship on data science.pdf'
 Karma_Yoga.xlsx
 Lambda_Filters_and_Map.ipynb
'let me see da....now itself after a few days befo....gsheet'
 List_Comprehension_in_python.ipynb
'Maths (1).jpeg'
'maths (1).jpg'
'maths (1).pdf'
'Maths (1).pdf'
'Maths (2).jpeg'
'Maths (2).pdf'
'Maths (3).jpeg'
'Maths (3).pdf'
'Maths (4).jpeg'
'Maths (4).pdf'
'Maths (5).pdf'
 Maths.jpeg
 maths.jpg
 maths.pdf
 Maths.pdf
'Maths test (1).pdf'
'Maths test (2).pdf'
'Maths test (3).pdf'
'Maths test (4).pdf'
'maths test.jpeg'
'maths test.pdf'
'Maths test.pdf'
'migration certificate.jpg'
'Neo4j (1).docx.pdf'
 Neo4j.docx.pdf
'New Static GK 2026 Updated (1).pdf'
'New Static GK 2026 Updated.pdf'
'now i need totally avoid her....right.....sometim....gsheet'
'online course.gsheet'
'payment_receipt (1).pdf'
 payment_receipt.pdf
'PEM 5th UNIT.docx.pdf'
'Personal memoranda.pdf'
'Photo from Bhargavi'
'Photo from Bhargavi (1)'
'Photo from Bhargavi (2)'
'Photo from Bhargavi (3)'
'Photo from Kalyan'
'Physics (1).jpeg'
'physics (1).jpg'
'physics (1).pdf'
'Physics (1).pdf'
'Physics (2).jpeg'
'physics (2).jpg'
'physics (3).jpg'
 physics.jpeg
 Physics.jpeg
 physics.jpg
 Physics.jpg
 physics.pdf
 Physics.pdf
'physics test (1).pdf'
'Physics test (1).pdf'
'Physics test (2).pdf'
'Physics test (3).pdf'
'Physics test (4).pdf'
'Physics test (5).pdf'
'Physics test-7.pdf'
'physics test.pdf'
'Physics test.pdf'
 provisional_certificate.jpg
'purpose statements (1).jpg'
'purpose statements.jpg'
'PYTHON LIBRARIES.gdoc'
'PYTHON LIBRARIES.pdf'
 Regular_Expressions_in_python.ipynb
'Resume Kalyan_PM.docx'
 Screenshot_20210108-154456.jpeg
 sdg.jpg
'Transfer_Certificate (1).jpg'
'transfer_certificate (1).pdf'
 Transfer_Certificate.jpg
 transfer_certificate.pdf
'UG_Marksheets (1).pdf'
 UG_Marksheets_BHARGAVI.pdf
 UG_Marksheets.pdf
'uhv 3.pdf'
'UHV Handout 1-Introduction to Value Education (1) (1).pdf'
'UHV Handout 2-Harmony in the Human Being.pdf'
'UHV Handout 4-Harmony in the Society.pdf'
'UHV Handout 5-Harmony in the Nature and Existence.pdf'
'uhv ques bank (1).pdf'
 UHV_UNIT4.pdf
 UHV_UNIT5.pdf
 ULIPRPR_XXXXXXX6604_26042022_8032.pdf
'unit 4 - part 2.pdf'
'Untitled Folder'
'Untitled Jam.pdf'
'Untitled spreadsheet (1).gsheet'
'Untitled spreadsheet.gsheet'
 VID-20201212-WA0031.mp4
 VID-20240415-WA0019.mp4
'Video from Bhargavi'
'Video from Kalyan'
'Video from Kalyan (1)'
'videoplayback (2).mp4'
'voj-wguc-yed - Nov 5, 2020.pdf'
'Weekly progress report.gsheet'
'Weekly progress report.xlsx'
'XII_MARK (1).pdf'
'XII_MARK (3).pdf'
 XII_MARK.pdf
'XII-maths delted portion - krishna.pdf'
'X_MARK (1).pdf'
'X_MARK (2).pdf'
 X_MARK.pdf

In [15]:
!ls /content/drive/MyDrive/crypto_project

app.py		    crypto_market_data.csv  oil_prices.csv
bitcoin_prices.csv  market_analysis.db	    stock_prices.csv

In [16]:
import pandas as pd

crypto = pd.read_csv('/content/drive/MyDrive/crypto_project/crypto_market_data.csv')
crypto

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,67959.000000,1360439595564,1,4.521852e+10,1.999980e+07,1.999980e+07,126080.000,67.810000,2026-03-09T10:14:21.079Z
1,ethereum,eth,Ethereum,2002.580000,241854145730,2,2.130865e+10,1.206920e+08,1.206920e+08,4946.050,0.432979,2026-03-09T10:14:21.489Z
2,tether,usdt,Tether,0.999815,183868914606,3,7.051148e+10,1.839095e+11,1.893765e+11,1.320,0.572521,2026-03-09T10:14:17.427Z
3,binancecoin,bnb,BNB,627.760000,85608529251,4,8.605146e+08,1.363584e+08,1.363584e+08,1369.990,0.039818,2026-03-09T10:14:20.825Z
4,ripple,xrp,XRP,1.350000,82948632505,5,2.200705e+09,6.122783e+10,9.998570e+10,3.650,0.002686,2026-03-09T10:14:16.732Z
...,...,...,...,...,...,...,...,...,...,...,...,...
245,akash-network,akt,Akash Network,0.383594,111634638,246,1.328202e+07,2.892543e+08,2.894799e+08,8.070,0.164994,2026-03-09T10:14:17.682Z
246,quantum-resistant-ledger,qrl,Quantum Resistant Ledger,1.390000,109810815,247,1.076470e+05,7.839296e+07,7.839296e+07,3.870,0.041170,2026-03-09T10:14:17.840Z
247,cash-4,cash,CASH,1.000000,108473596,248,1.354805e+07,1.084558e+08,1.084558e+08,1.058,0.975346,2026-03-09T10:14:17.709Z
248,precious-metals-usd,pmusd,Precious Metals USD,0.988173,108425417,249,9.749350e+05,1.097012e+08,1.097012e+08,1.037,0.955534,2026-03-09T10:14:17.717Z
249,cap-usd,cusd,Cap USD,1.001000,108422522,250,1.052640e+05,1.091973e+08,1.091973e+08,1.170,0.946058,2026-03-09T10:14:17.692Z

In [17]:
import sqlite3
conn = sqlite3.connect(
"/content/drive/MyDrive/crypto_project/market_analysis.db"
)

In [18]:
import os
os.listdir()

['.config',
 'drive',
 'crypto_market_data.csv',
 'oil_prices.csv',
 'bitcoin_prices.csv',
 'stock_prices.csv',
 'sample_data']

In [19]:
import sqlite3
conn = sqlite3.connect(
"/content/drive/MyDrive/crypto_project/market_analysis.db"
)

crypto.to_sql("cryptocurrencies", conn, if_exists="replace", index=False)
oil.to_sql("oil_prices", conn, if_exists="replace", index=False)
stocks.to_sql("stock_prices", conn, if_exists="replace", index=False)
btc.to_sql("bitcoin_prices", conn, if_exists="replace", index=False)

print("Tables created successfully")

Tables created successfully

In [20]:
import os
print(os.getcwd())

/content

In [21]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
pd.read_sql(query, conn)

               name
0  cryptocurrencies
1        oil_prices
2      stock_prices
3    bitcoin_prices

In [22]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
pd.read_sql(query, conn)

               name
0  cryptocurrencies
1        oil_prices
2      stock_prices
3    bitcoin_prices

In [23]:
query = """
SELECT MAX(price) AS highest_oil_price
FROM oil_prices;
"""

pd.read_sql(query, conn)

   highest_oil_price
0             145.31

In [24]:
query = """
SELECT AVG(close) AS avg_sp500_close
FROM stock_prices
WHERE ticker = '^GSPC';
"""

pd.read_sql(query, conn)

   avg_sp500_close
0      4259.606933

In [25]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(
"/content/drive/MyDrive/crypto_project/market_analysis.db"
)

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)

print(tables)

               name
0  cryptocurrencies
1        oil_prices
2      stock_prices
3    bitcoin_prices

In [26]:
query = """
SELECT name, symbol, market_cap
FROM cryptocurrencies
ORDER BY market_cap DESC
LIMIT 3;
"""

pd.read_sql(query, conn)

       name symbol     market_cap
0   Bitcoin    btc  1360439595564
1  Ethereum    eth   241854145730
2    Tether   usdt   183868914606

In [27]:
query = """
SELECT name, circulating_supply, total_supply
FROM cryptocurrencies
WHERE circulating_supply > 0.9 * total_supply;
"""

pd.read_sql(query, conn)

                         name  circulating_supply  total_supply
0                     Bitcoin        1.999980e+07  1.999980e+07
1                    Ethereum        1.206920e+08  1.206920e+08
2                      Tether        1.839095e+11  1.893765e+11
3                         BNB        1.363584e+08  1.363584e+08
4                        USDC        7.721066e+10  7.721120e+10
..                        ...                 ...           ...
138             Akash Network        2.892543e+08  2.894799e+08
139  Quantum Resistant Ledger        7.839296e+07  7.839296e+07
140                      CASH        1.084558e+08  1.084558e+08
141       Precious Metals USD        1.097012e+08  1.097012e+08
142                   Cap USD        1.091973e+08  1.091973e+08

[143 rows x 3 columns]

In [28]:
query = """
SELECT name, ath, current_price
FROM cryptocurrencies
WHERE current_price >= 0.9 * ath;
"""

pd.read_sql(query, conn)

,name,ath,current_price
0,USDC,1.043000,0.999998
1,Figure Heloc,1.038000,1.024000
2,USDS,1.057000,0.999518
3,Ethena USDe,1.034000,0.999219
4,USD1,1.025000,0.999297
5,PayPal USD,1.021000,0.999944
6,Tether Gold,5504.620000,5079.460000
7,PAX Gold,5619.090000,5119.120000
8,Circle USYC,1.120000,1.120000
9,BlackRock USD Institutional Digital Liquidity ...,1.000000,1.000000
10,Falcon USD,1.075000,0.998132
11,Ripple USD,1.073000,0.999973
12,BFUSD,1.007000,0.999009
13,Superstate Short Duration U.S. Government Secu...,11.010000,11.010000
14,Spiko EU T-Bills Money Market Fund,1.260000,1.210000
15,USDtb,1.057000,0.999627
16,OUSG,114.500000,114.500000
17,Janus Henderson Anemoy AAA CLO Fund,1.028000,1.026000
18,USDD,1.052000,0.999120
19,YLDS,1.001000,0.999939
20,Janus Henderson Anemoy Treasury Fund,1.096000,1.096000
21,GHO,1.030000,1.000000
22,USX,1.038000,0.999615
23,PRIME,1.026000,1.022000
24,Neutrl USD,1.031000,0.999669
25,USDa,1.021000,0.984042
26,AUSD,1.022000,1.000000
27,Spiko US T-Bills Money Market Fund,1.076000,1.076000
28,The9bit,0.022345,0.022079
29,Fidelity Digital Interest Token,1.000000,1.000000
30,coco,0.157989,0.157631
31,GUSD,1.022000,0.999111
32,Aster USDF,1.046000,0.999249
33,Theo Short Duration US Treasury Fund,1.110000,1.014000
34,Apollo Diversified Credit Securitize Fund,1108.470000,1095.300000
35,Onchain Yield Coin,1.083000,1.083000
36,Pleasing USD,1.057000,1.004000
37,Re Protocol reUSD,1.078000,1.065000
38,Frax USD,1.007000,1.000000
39,Avant USD,1.059000,0.999659
40,CASH,1.058000,1.000000
41,Precious Metals USD,1.037000,0.988173

In [29]:
query = """
SELECT name, ath, current_price
FROM cryptocurrencies
WHERE current_price >= 0.9 * ath;
"""

pd.read_sql(query, conn)

,name,ath,current_price
0,USDC,1.043000,0.999998
1,Figure Heloc,1.038000,1.024000
2,USDS,1.057000,0.999518
3,Ethena USDe,1.034000,0.999219
4,USD1,1.025000,0.999297
5,PayPal USD,1.021000,0.999944
6,Tether Gold,5504.620000,5079.460000
7,PAX Gold,5619.090000,5119.120000
8,Circle USYC,1.120000,1.120000
9,BlackRock USD Institutional Digital Liquidity ...,1.000000,1.000000
10,Falcon USD,1.075000,0.998132
11,Ripple USD,1.073000,0.999973
12,BFUSD,1.007000,0.999009
13,Superstate Short Duration U.S. Government Secu...,11.010000,11.010000
14,Spiko EU T-Bills Money Market Fund,1.260000,1.210000
15,USDtb,1.057000,0.999627
16,OUSG,114.500000,114.500000
17,Janus Henderson Anemoy AAA CLO Fund,1.028000,1.026000
18,USDD,1.052000,0.999120
19,YLDS,1.001000,0.999939
20,Janus Henderson Anemoy Treasury Fund,1.096000,1.096000
21,GHO,1.030000,1.000000
22,USX,1.038000,0.999615
23,PRIME,1.026000,1.022000
24,Neutrl USD,1.031000,0.999669
25,USDa,1.021000,0.984042
26,AUSD,1.022000,1.000000
27,Spiko US T-Bills Money Market Fund,1.076000,1.076000
28,The9bit,0.022345,0.022079
29,Fidelity Digital Interest Token,1.000000,1.000000
30,coco,0.157989,0.157631
31,GUSD,1.022000,0.999111
32,Aster USDF,1.046000,0.999249
33,Theo Short Duration US Treasury Fund,1.110000,1.014000
34,Apollo Diversified Credit Securitize Fund,1108.470000,1095.300000
35,Onchain Yield Coin,1.083000,1.083000
36,Pleasing USD,1.057000,1.004000
37,Re Protocol reUSD,1.078000,1.065000
38,Frax USD,1.007000,1.000000
39,Avant USD,1.059000,0.999659
40,CASH,1.058000,1.000000
41,Precious Metals USD,1.037000,0.988173

In [30]:
query = """
SELECT name, last_updated
FROM cryptocurrencies
ORDER BY last_updated DESC
LIMIT 1;
"""

pd.read_sql(query, conn)

            name              last_updated
0  Axie Infinity  2026-03-09T10:14:23.989Z

In [31]:
query = """
SELECT AVG(price_usd) AS avg_btc_price
FROM bitcoin_prices;
"""

pd.read_sql(query, conn)

   avg_btc_price
0   98275.810327

In [32]:
query = """
SELECT
(MAX(price_usd) - MIN(price_usd)) * 100.0 / MIN(price_usd) AS percent_change
FROM bitcoin_prices;
"""

pd.read_sql(query, conn)

   percent_change
0       98.514212

In [33]:
query = """
SELECT MAX(price) AS highest_oil_price
FROM oil_prices;
"""

pd.read_sql(query, conn)

   highest_oil_price
0             145.31

In [34]:
query = """
SELECT SUBSTR(date,1,4) AS year,
AVG(price) AS avg_price
FROM oil_prices
GROUP BY year;
"""

pd.read_sql(query, conn)

    year  avg_price
0   1986  15.047689
1   1987  19.200512
2   1988  15.965409
3   1989  19.635486
4   1990  24.526576
5   1991  21.541367
6   1992  20.575564
7   1993  18.432200
8   1994  17.196429
9   1995  18.428805
10  1996  22.119173
11  1997  20.608254
12  1998  14.422072
13  1999  19.344980
14  2000  30.378520
15  2001  25.983120
16  2002  26.184960
17  2003  31.075240
18  2004  41.506024
19  2005  56.637251
20  2006  66.054659
21  2007  72.340595
22  2008  99.671502
23  2009  61.950437
24  2010  79.475714
25  2011  94.880873
26  2012  94.053333
27  2013  97.982540
28  2014  93.172222
29  2015  48.656706
30  2016  43.293651
31  2017  50.800320
32  2018  65.227470
33  2019  56.988320
34  2020  39.160437
35  2021  68.135100
36  2022  94.902869
37  2023  77.576532
38  2024  76.632240
39  2025  65.388105
40  2026  62.438250

In [35]:
query = """
SELECT
SUBSTR(date,1,4) AS year,
(MAX(price) - MIN(price)) AS volatility
FROM oil_prices
GROUP BY year;
"""

pd.read_sql(query, conn)

    year  volatility
0   1986       16.28
1   1987        7.32
2   1988        5.96
3   1989        7.63
4   1990       25.64
5   1991       14.82
6   1992        5.14
7   1993        7.07
8   1994        6.83
9   1995        3.67
10  1996        9.22
11  1997        8.95
12  1998        7.11
13  1999       16.65
14  2000       13.31
15  2001       14.71
16  2002       14.66
17  2003       12.71
18  2004       23.88
19  2005       27.75
20  2006       21.15
21  2007       48.65
22  2008      115.03
23  2009       47.00
24  2010       26.70
25  2011       37.99
26  2012       31.67
27  2013       23.97
28  2014       54.50
29  2015       26.81
30  2016       27.82
31  2017       17.98
32  2018       32.93
33  2019       19.93
34  2020      100.25
35  2021       38.17
36  2022       52.59
37  2023       27.06
38  2024       20.96
39  2025       25.29
40  2026       15.12

In [36]:
query = """
SELECT MAX(close)
FROM stock_prices
WHERE ticker='^IXIC';
"""

pd.read_sql(query, conn)

     MAX(close)
0  20173.890625

In [37]:
query = """
SELECT date,
(high - low) AS price_difference
FROM stock_prices
WHERE ticker='^GSPC'
ORDER BY price_difference DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

         Date  price_difference
0  2020-03-13        218.959961
1  2024-12-18        202.879883
2  2022-01-24        194.729980
3  2022-10-13        193.829834
4  2020-03-17        186.889893

In [38]:
query = """
SELECT SUBSTR(date,1,7) AS month,
AVG(close) AS avg_close
FROM stock_prices
GROUP BY month;
"""

pd.read_sql(query, conn)

      month     avg_close
0   2020-01   8353.127963
1   2020-02   8214.995130
2   2020-03   6573.749831
3   2020-04   6588.108842
4   2020-05   7036.500459
5   2020-06   7687.028979
6   2020-07   8241.964188
7   2020-08   8640.855736
8   2020-09   8639.774651
9   2020-10   8836.468457
10  2020-11   9256.530191
11  2020-12   9954.933934
12  2021-01  10488.254824
13  2021-02  10929.874651
14  2021-03  10512.857641
15  2021-04  10762.903208
16  2021-05  10890.534530
17  2021-06  11356.445276
18  2021-07  11595.294441
19  2021-08  11857.081363
20  2021-09  12325.898724
21  2021-10  12363.524320
22  2021-11  12653.331582
23  2021-12  12511.801437
24  2022-01  12291.938468
25  2022-02  11946.177052
26  2022-03  11470.034333
27  2022-04  11638.593800
28  2022-05  10713.702885
29  2022-06  10503.199715
30  2022-07  10704.371622
31  2022-08  11156.730894
32  2022-09  11036.063763
33  2022-10  10423.099173
34  2022-11  11067.470002
35  2022-12  11160.184601
36  2023-01  11095.681909
37  2023-02  11314.049468
38  2023-03  10756.246021
39  2023-04  11068.822994
40  2023-05  11633.252763
41  2023-06  12178.640788
42  2023-07  12821.792376
43  2023-08  12444.933141
44  2023-09  12593.659888
45  2023-10  12092.930138
46  2023-11  12546.688705
47  2023-12  13513.838501
48  2024-01  13840.211441
49  2024-02  14382.143907
50  2024-03  14257.204447
51  2024-04  14254.109230
52  2024-05  14633.031325
53  2024-06  15425.025622
54  2024-07  15998.815888
55  2024-08  15650.725916
56  2024-09  16381.667424
57  2024-10  16172.020651
58  2024-11  16156.815868
59  2024-12  16658.823157

In [39]:
query = """
SELECT SUBSTR(date,1,7) AS month,
AVG(close) AS avg_close
FROM stock_prices
GROUP BY month;
"""

pd.read_sql(query, conn)

      month     avg_close
0   2020-01   8353.127963
1   2020-02   8214.995130
2   2020-03   6573.749831
3   2020-04   6588.108842
4   2020-05   7036.500459
5   2020-06   7687.028979
6   2020-07   8241.964188
7   2020-08   8640.855736
8   2020-09   8639.774651
9   2020-10   8836.468457
10  2020-11   9256.530191
11  2020-12   9954.933934
12  2021-01  10488.254824
13  2021-02  10929.874651
14  2021-03  10512.857641
15  2021-04  10762.903208
16  2021-05  10890.534530
17  2021-06  11356.445276
18  2021-07  11595.294441
19  2021-08  11857.081363
20  2021-09  12325.898724
21  2021-10  12363.524320
22  2021-11  12653.331582
23  2021-12  12511.801437
24  2022-01  12291.938468
25  2022-02  11946.177052
26  2022-03  11470.034333
27  2022-04  11638.593800
28  2022-05  10713.702885
29  2022-06  10503.199715
30  2022-07  10704.371622
31  2022-08  11156.730894
32  2022-09  11036.063763
33  2022-10  10423.099173
34  2022-11  11067.470002
35  2022-12  11160.184601
36  2023-01  11095.681909
37  2023-02  11314.049468
38  2023-03  10756.246021
39  2023-04  11068.822994
40  2023-05  11633.252763
41  2023-06  12178.640788
42  2023-07  12821.792376
43  2023-08  12444.933141
44  2023-09  12593.659888
45  2023-10  12092.930138
46  2023-11  12546.688705
47  2023-12  13513.838501
48  2024-01  13840.211441
49  2024-02  14382.143907
50  2024-03  14257.204447
51  2024-04  14254.109230
52  2024-05  14633.031325
53  2024-06  15425.025622
54  2024-07  15998.815888
55  2024-08  15650.725916
56  2024-09  16381.667424
57  2024-10  16172.020651
58  2024-11  16156.815868
59  2024-12  16658.823157

In [40]:
import os

os.listdir("/content/drive/MyDrive/crypto_project")

['app.py',
 '.ipynb_checkpoints',
 'bitcoin_prices.csv',
 'crypto_market_data.csv',
 'stock_prices.csv',
 'oil_prices.csv',
 'market_analysis.db']